### ISSUE TITLE
Download button does not appear on the site

### ISSUE THREAD

**Issue by behnamFarhadi** [nvqc86/extract_subtitle_from_pluralsight#1]
in fact,Download button does not appear on the site,It does not work.

**Comment by nvqc86** [comment]
Issue has been fixed. Please clone and follow the instruction again. Thanks

**Comment by behnamFarhadi** [comment]
But still, it doesn't work for me, there's no Download Button, i also changed the time (for instance 3 10 20 seconds) but it didn't work out,Used Firefix and Chrome as well and didn't get any different result and the internet speed is good.

**Comment by nvqc86** [comment]
01 install tampermonkey on chrome
![01 install tampermonkey on chrome](https://cloud.githubusercontent.com/assets/4695439/15913170/51cfc1ca-2d8d-11e6-8454-b9586d4cd7dd.png)

02 add script to tampermonkey on chrome
![02 add script to tampermonkey on chrome](https://cloud.githubusercontent.com/assets/4695439/15913168/51cf1766-2d8d-11e6-9a8e-ae6b76f5f90b.png)

03 paste script from github and click save button
![03 paste script from github and click save button](https://cloud.githubusercontent.com/assets/4695439/15913169/51cf4484-2d8d-11e6-9f89-a1a057489d65.png)

04 go to transcript tab refresh browser create link and download
![04 go to transcript tab refresh browser create link and download](https://cloud.githubusercontent.com/assets/4695439/15913171/51d092d0-2d8d-11e6-9e9d-88916d443350.png)

Sorry that I haven't test it yet. Problem now has been fixed and tested

**Comment by farhadibehnam** [comment]
thanks has been worked.
